### ISSUE TITLE
Using markdown icon for markup files

### ISSUE THREAD

**Issue by musthbly** [artlaman/chalice-icon-theme#12]
**Is your feature request related to a problem? Please describe.**
Markup files (e.g. `*.org` or `*.rst`) are given the "other" icon.

**Describe the solution you'd like**
Give all markup files the markdown icon, since they serve a similar purpose.

**Describe alternatives you've considered**
None

**Additional context**
Screenshot:
<img width="100" alt="Markup files" src="https://user-images.githubusercontent.com/69535511/114392850-567e8100-9b67-11eb-9e83-c822eac2a369.png">

**Comment by artlaman** [comment]
I agree. 😊
Will try to fix it during this week, but you are welcome to submit a merge request yourself
