### ISSUE TITLE
Can't find this extension in the Marketplace

### ISSUE THREAD

**Issue by illright** [artlaman/chalice-icon-theme#13]
**Describe the bug**
I want to install this icon pack, but nothing comes up on search inside the extensions manager of VSCodium.

**To Reproduce**
1. Search for `Chalice` in the extensions manager
2. Find nothing

I'd like to emphasize that I am using VSCodium, not VSCode, though I don't think this should make a difference. My OS is Manjaro Linux.

**Comment by artlaman** [comment]
It appears VSCodium uses [OpenVSX](https://open-vsx.org/) extension marketplace instead of [Microsoft marketplace](https://marketplace.visualstudio.com/).
I'll try to figure out how to make `Chalice` available on OpenVSX

**Comment by artlaman** [comment]
@illright Extensions are now available on OpenVSX 🙂

**Comment by illright** [comment]
I must confess, I already installed VS Code instead (to get the new Pylance extension for Python), but I appreciate your effort :)
