### ISSUE TITLE
Add icons for Svelte and mdsvex files

### ISSUE THREAD

**Issue by illright** [artlaman/chalice-icon-theme#15]
[Svelte](https://svelte.dev) is a JS framework and a superset of HTML, so I'd say that the "XML" icon is the most suitable for `.svelte` files.
[mdsvex](https://mdsvex.com/) is a library for Svelte that allows writing Markdown files with Svelte components inside, so it's probably the "Markdown" icon for `.svx` files.

Would love to see icons for these file types!

**Comment by artlaman** [comment]
Done!
Thanks for suggestion
