### ISSUE TITLE
icon for settings menu / extensions

### ISSUE THREAD

**Issue by 1e1001** [artlaman/chalice-icon-theme#16]
currently the settings ui and open extension tabs use the generic file icon like this:
![image](https://user-images.githubusercontent.com/22437115/122866344-a2bf0d80-d2dc-11eb-9f18-7725882f4f32.png)
i feel like these would be better if they had their own icon (or at least used a different icon)

**Comment by artlaman** [comment]
Hey!
I don't think that's even possible currently 🙂

**Comment by 1e1001** [comment]
Ah ok, I guess I'll close this issue then.
