### ISSUE TITLE
jsonl association with json-like icon

### ISSUE THREAD

**Issue by adamkgoldfarb** [artlaman/chalice-icon-theme#19]
**Is your feature request related to a problem? Please describe.**
.jsonl files are associated with the icon for "Regular files that don’t fall into other categories."

**Describe the solution you'd like**
.jsonl files are instead associated with the icon for json-like files.

**Describe alternatives you've considered**
I took a spin through the source but couldn't immediately identify where associations are defined-- if you want to point me there I could submit a pull request.

**Additional context**
Thanks for this awesome icon pack!

**Comment by artlaman** [comment]
> Thanks for this awesome icon pack!

Oh, thank you! 🙂

>  if you want to point me there I could submit a pull request.

Associations are defined at [chalice-icon-theme.json](https://github.com/artlaman/chalice-icon-theme/blob/master/chalice-icon-theme.json) You have to basically add two associations: for light (normal) and dark (inverse) themes. Check pull request #9 for an example. Or, I can make a pull request myself this week I believe.

**Comment by artlaman** [comment]
Thank you very much. New extension version should be already available for use in Visual Studio Marketplace
