### ISSUE TITLE
groovy language file extension is not covered

### ISSUE THREAD

**Issue by baoqianz** [artlaman/chalice-icon-theme#22]
**Describe the bug**
groovy language file extension is not covered.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by artlaman** [comment]
Thank you. I've added bindings for `.groovy`, `.gvy`, `.gy`, `.gsh` file extensions.

**Comment by baoqianz** [comment]
Thanks for quick fix!
