### ISSUE TITLE
icons collide with text in route autocomplete menu

### ISSUE THREAD

**Issue by ivanlegranbizarro** [artlaman/chalice-icon-theme#28]
**Describe the bug**
icons collide with text in autocomplete path menu.

**To Reproduce**
indicate a path in the text editor by opening quotes, for example
import xxx from './'

**Screenshots**
![Captura de Pantalla 2022-07-26 a las 17 42 55](https://user-images.githubusercontent.com/68439095/181051256-892e5a9f-97b6-43b0-94a9-c316cb7d71cd.png)

**Desktop (please complete the following information):**
I use the last stable version of VSCODE. My machine is a Mac Os with M1.

**Additional context**
I have tried to modify the zoom in Vscode and the size of the fonts, but the icons always appear as I show in the attached image.

**Comment by artlaman** [comment]
I'm too running the latest stable version of vscode on M1 mac, and I managed to reproduce this bug only by changing the font size to very large. Suppose some of your font settings is causing the issue.
Try adding these lines to the end of `settings.json`. Does it help?
```
  "editor.fontFamily": "Monaco",
  "editor.fontWeight": "400",
  "editor.letterSpacing": 0,
  "window.zoomLevel": 0,
  "editor.fontSize": 12,
```
<img width="300" alt="Screenshot 2022-07-27 at 22 26 14" src="https://user-images.githubusercontent.com/7010178/181355556-98940675-5252-42a0-8332-248f7a68f086.png">
