### ISSUE TITLE
Is it possible to make the icons match the text color when a row is selected?

### ISSUE THREAD

**Issue by garettbass** [artlaman/chalice-icon-theme#3]
The grey color of the icons on a light theme matches the text color, but when a row in the explorer is selected, the grey has very low contrast with the blue selection background.  If possible, it would be great to see the icons match the lighter text color when the row is selected.

![image](https://user-images.githubusercontent.com/561106/63365956-8abb8300-c32d-11e9-9f45-6fb4c3d775d6.png)

**Comment by garettbass** [comment]
Love this theme, by the way, reviewed and rated 5 stars.

**Comment by artlaman** [comment]
Unfortunately it is not possible. And 
I ran into the same issue: I used to use [Alabaster Theme](https://marketplace.visualstudio.com/items?itemName=tonsky.theme-alabaster) (which also uses blue selection background) and I didn't like it either. So one of the reasons why I decided to create [Chalice Color Theme](https://marketplace.visualstudio.com/items?itemName=artlaman.chalice-color-theme) is to change the color of the selection background. You can try my theme (warning! it's inspired by Alabaster so it uses minimal amount of highlighting). Or any other theme which uses different colors for selection. Or fork default theme.
