### ISSUE TITLE
HCL to configuration languages

### ISSUE THREAD

**Issue by endigma** [artlaman/chalice-icon-theme#32]
The official HCL extension adds an ugly icon that gets used because chalice doesn't explicitly set it

**Comment by endigma** [comment]
Perhaps the packer and tf file extensions too, they are also HCL. It probably fits best into JSON-like.

**Comment by artlaman** [comment]
I read the docs and there are 5 file formats used by HCL: `.hcl` `.tf` `.tf.json` `.pkr.hcl` `.pkr.json`.
If I understood everything correctly only the ones ending with `.json` have json-like syntax. I checked, and everything seems fine,  the `<>`icon  displayed next to them.

Considering that the syntax of .hcl, .tf, and .pkr.hcl looks similar to yaml, it may be appropriate to categorize them under the script category (/*). What do you think? @endigma

**Comment by endigma** [comment]
They don't at all look like yaml in my opinion, but I honestly don't care what icon you give it as long as the default one goes away.

**Comment by endigma** [comment]
```hcl
io_mode = "async"

service "http" "web_proxy" {
  listen_addr = "127.0.0.1:8080"
  
  process "main" {
    command = ["/usr/local/bin/awesome-app", "server"]
  }

  process "mgmt" {
    command = ["/usr/local/bin/awesome-app", "mgmt"]
  }
}
```

This is the example code for HCL2, it uses `=` and `{}`, so I figure it fits in with JSON, HJSON, JSONNET, etc, but the script icon is fine.
