### ISSUE TITLE
Dart files aren't considered code

### ISSUE THREAD

**Issue by vhgn** [artlaman/chalice-icon-theme#6]
**Describe the bug**
Dart files are shown as regular files, not code.

**Expected behavior**
It was expected to be with code icons (`/*`).

**Screenshots**
<img width="103" alt="Screen Shot 2020-03-22 at 16 37 17" src="https://user-images.githubusercontent.com/36004230/77249565-66c17680-6c5b-11ea-964d-4621e1f257b7.png">

---

Additionally, I expected `yaml` files to have special icons (`json` has, `xml` has), but, I guess, it doesn't fall into any category.

**Comment by artlaman** [comment]
How could I forget about dart. 😅
Thank you. Will add it to `/*` category soon.

**Comment by artlaman** [comment]
Done.
As of yaml, I'll look into it.

**Comment by vhgn** [comment]
Ok, I am closing the issue, as the `dart` files are fixed. `{}` doesn't fit `yaml`, so it's a secondary problem and totally up to you.

Thanks
